services:
  spark-master:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: retailx-spark-master
    command: >
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.master.Master
      --host spark-master
      --port 7077
      --webui-port 8080
    environment:
      - APP_HOME=/opt/spark/work-dir/app
      - SPARK_MASTER_URL=spark://spark-master:7077
      - RETAILX_ROWS=1000000
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - .:/opt/spark/work-dir/app
    networks:
      - retailx-net

  spark-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: retailx-spark-worker
    depends_on:
      - spark-master
    command: >
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.worker.Worker
      spark://spark-master:7077
      --webui-port 8081
    environment:
      - APP_HOME=/opt/spark/work-dir/app
      - SPARK_MASTER_URL=spark://spark-master:7077
    ports:
      - "8082:8081"
    volumes:
      - .:/opt/spark/work-dir/app
    networks:
      - retailx-net

  kafka:
    image: apache/kafka:3.9.2
    container_name: retailx-kafka
    ports:
      - "29092:29092"
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_LISTENERS=PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093,EXTERNAL://0.0.0.0:29092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:29092
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - CLUSTER_ID=abcdefghijklmnopqrstuv
    networks:
      - retailx-net

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: retailx-kafka-ui
    depends_on:
      - kafka
    ports:
      - "8081:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=retailx-local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    networks:
      - retailx-net

networks:
  retailx-net:
    driver: bridge